<?php
/**
* Google font list from https://fonts.google.com/
*/

global $llp_google_fonts;

$llp_font_array = array(
	'ABeeZee',
	'Abel',
	'Abhaya Libre',
	'Abril Fatface',
	'Aclonica',
	'Acme',
	'Actor',
	'Adamina',
	'Advent Pro',
	'Aguafina Script',
	'Akronim',
	'Aladin',
	'Aldrich',
	'Alef',
	'Alegreya SC',
	'Alegreya Sans SC',
	'Alegreya Sans',
	'Alegreya',
	'Alex Brush',
	'Alfa Slab One',
	'Alice',
	'Alike Angular',
	'Alike',
	'Allan',
	'Allerta Stencil',
	'Allerta',
	'Allura',
	'Almendra Display',
	'Almendra SC',
	'Almendra',
	'Amarante',
	'Amaranth',
	'Amatic SC',
	'Amethysta',
	'Amiko',
	'Amiri',
	'Amita',
	'Anaheim',
	'Andada',
	'Andika',
	'Angkor',
	'Annie Use Your Telescope',
	'Anonymous Pro',
	'Antic Didone',
	'Antic Slab',
	'Antic',
	'Anton',
	'Arapey',
	'Arbutus Slab',
	'Arbutus',
	'Architects Daughter',
	'Archivo Black',
	'Archivo Narrow',
	'Archivo',
	'Aref Ruqaa',
	'Arima Madurai',
	'Arimo',
	'Arizonia',
	'Armata',
	'Arsenal',
	'Artifika',
	'Arvo',
	'Arya',
	'Asap Condensed',
	'Asap',
	'Asar',
	'Asset',
	'Assistant',
	'Astloch',
	'Asul',
	'Athiti',
	'Atma',
	'Atomic Age',
	'Aubrey',
	'Audiowide',
	'Autour One',
	'Average Sans',
	'Average',
	'Averia Gruesa Libre',
	'Averia Libre',
	'Averia Sans Libre',
	'Averia Serif Libre',
	'Bad Script',
	'Bahiana',
	'Baloo Bhai',
	'Baloo Bhaijaan',
	'Baloo Bhaina',
	'Baloo Chettan',
	'Baloo Da',
	'Baloo Paaji',
	'Baloo Tamma',
	'Baloo Tammudu',
	'Baloo Thambi',
	'Baloo',
	'Balthazar',
	'Bangers',
	'Barlow Condensed',
	'Barlow Semi Condensed',
	'Barlow',
	'Barrio',
	'Basic',
	'Battambang',
	'Baumans',
	'Bayon',
	'Belgrano',
	'Bellefair',
	'Belleza',
	'BenchNine',
	'Bentham',
	'Berkshire Swash',
	'Bevan',
	'Bigelow Rules',
	'Bigshot One',
	'Bilbo Swash Caps',
	'Bilbo',
	'BioRhyme Expanded',
	'BioRhyme',
	'Biryani',
	'Bitter',
	'Black And White Picture',
	'Black Han Sans',
	'Black Ops One',
	'Bokor',
	'Bonbon',
	'Boogaloo',
	'Bowlby One SC',
	'Bowlby One',
	'Brawler',
	'Bree Serif',
	'Bubblegum Sans',
	'Bubbler One',
	'Buda',
	'Buenard',
	'Bungee Hairline',
	'Bungee Inline',
	'Bungee Outline',
	'Bungee Shade',
	'Bungee',
	'Butcherman',
	'Butterfly Kids',
	'Cabin Condensed',
	'Cabin Sketch',
	'Cabin',
	'Caesar Dressing',
	'Cagliostro',
	'Cairo',
	'Calligraffitti',
	'Cambay',
	'Cambo',
	'Candal',
	'Cantarell',
	'Cantata One',
	'Cantora One',
	'Capriola',
	'Cardo',
	'Carme',
	'Carrois Gothic SC',
	'Carrois Gothic',
	'Carter One',
	'Catamaran',
	'Caudex',
	'Caveat Brush',
	'Caveat',
	'Cedarville Cursive',
	'Ceviche One',
	'Changa One',
	'Changa',
	'Chango',
	'Chathura',
	'Chau Philomene One',
	'Chela One',
	'Chelsea Market',
	'Chenla',
	'Cherry Cream Soda',
	'Cherry Swash',
	'Chewy',
	'Chicle',
	'Chivo',
	'Chonburi',
	'Cinzel Decorative',
	'Cinzel',
	'Clicker Script',
	'Coda Caption',
	'Coda',
	'Codystar',
	'Coiny',
	'Combo',
	'Comfortaa',
	'Coming Soon',
	'Concert One',
	'Condiment',
	'Content',
	'Contrail One',
	'Convergence',
	'Cookie',
	'Copse',
	'Corben',
	'Cormorant Garamond',
	'Cormorant Infant',
	'Cormorant SC',
	'Cormorant Unicase',
	'Cormorant Upright',
	'Cormorant',
	'Courgette',
	'Cousine',
	'Coustard',
	'Covered By Your Grace',
	'Crafty Girls',
	'Creepster',
	'Crete Round',
	'Crimson Text',
	'Croissant One',
	'Crushed',
	'Cuprum',
	'Cute Font',
	'Cutive Mono',
	'Cutive',
	'Damion',
	'Dancing Script',
	'Dangrek',
	'David Libre',
	'Dawning of a New Day',
	'Days One',
	'Dekko',
	'Delius Swash Caps',
	'Delius Unicase',
	'Delius',
	'Della Respira',
	'Denk One',
	'Devonshire',
	'Dhurjati',
	'Didact Gothic',
	'Diplomata SC',
	'Diplomata',
	'Do Hyeon',
	'Dokdo',
	'Domine',
	'Donegal One',
	'Doppio One',
	'Dorsa',
	'Dosis',
	'Dr Sugiyama',
	'Duru Sans',
	'Dynalight',
	'EB Garamond',
	'Eagle Lake',
	'East Sea Dokdo',
	'Eater',
	'Economica',
	'Eczar',
	'El Messiri',
	'Electrolize',
	'Elsie Swash Caps',
	'Elsie',
	'Emblema One',
	'Emilys Candy',
	'Encode Sans Condensed',
	'Encode Sans Expanded',
	'Encode Sans Semi Condensed',
	'Encode Sans Semi Expanded',
	'Encode Sans',
	'Engagement',
	'Englebert',
	'Enriqueta',
	'Erica One',
	'Esteban',
	'Euphoria Script',
	'Ewert',
	'Exo 2',
	'Exo',
	'Expletus Sans',
	'Fanwood Text',
	'Farsan',
	'Fascinate Inline',
	'Fascinate',
	'Faster One',
	'Fasthand',
	'Fauna One',
	'Faustina',
	'Federant',
	'Federo',
	'Felipa',
	'Fenix',
	'Finger Paint',
	'Fira Mono',
	'Fira Sans Condensed',
	'Fira Sans Extra Condensed',
	'Fira Sans',
	'Fjalla One',
	'Fjord One',
	'Flamenco',
	'Flavors',
	'Fondamento',
	'Fontdiner Swanky',
	'Forum',
	'Francois One',
	'Frank Ruhl Libre',
	'Freckle Face',
	'Fredericka the Great',
	'Fredoka One',
	'Freehand',
	'Fresca',
	'Frijole',
	'Fruktur',
	'Fugaz One',
	'GFS Didot',
	'GFS Neohellenic',
	'Gabriela',
	'Gaegu',
	'Gafata',
	'Galada',
	'Galdeano',
	'Galindo',
	'Gamja Flower',
	'Gentium Basic',
	'Gentium Book Basic',
	'Geo',
	'Geostar Fill',
	'Geostar',
	'Germania One',
	'Gidugu',
	'Gilda Display',
	'Give You Glory',
	'Glass Antiqua',
	'Glegoo',
	'Gloria Hallelujah',
	'Goblin One',
	'Gochi Hand',
	'Gorditas',
	'Gothic A1',
	'Goudy Bookletter 1911',
	'Graduate',
	'Grand Hotel',
	'Gravitas One',
	'Great Vibes',
	'Griffy',
	'Gruppo',
	'Gudea',
	'Gugi',
	'Gurajada',
	'Habibi',
	'Halant',
	'Hammersmith One',
	'Hanalei Fill',
	'Hanalei',
	'Handlee',
	'Hanuman',
	'Happy Monkey',
	'Harmattan',
	'Headland One',
	'Heebo',
	'Henny Penny',
	'Herr Von Muellerhoff',
	'Hi Melody',
	'Hind Guntur',
	'Hind Madurai',
	'Hind Siliguri',
	'Hind Vadodara',
	'Hind',
	'Holtwood One SC',
	'Homemade Apple',
	'Homenaje',
	'IBM Plex Mono',
	'IBM Plex Sans Condensed',
	'IBM Plex Sans',
	'IBM Plex Serif',
	'IM Fell DW Pica SC',
	'IM Fell DW Pica',
	'IM Fell Double Pica SC',
	'IM Fell Double Pica',
	'IM Fell English SC',
	'IM Fell English',
	'IM Fell French Canon SC',
	'IM Fell French Canon',
	'IM Fell Great Primer SC',
	'IM Fell Great Primer',
	'Iceberg',
	'Iceland',
	'Imprima',
	'Inconsolata',
	'Inder',
	'Indie Flower',
	'Inika',
	'Inknut Antiqua',
	'Irish Grover',
	'Istok Web',
	'Italiana',
	'Italianno',
	'Itim',
	'Jacques Francois Shadow',
	'Jacques Francois',
	'Jaldi',
	'Jim Nightshade',
	'Jockey One',
	'Jolly Lodger',
	'Jomhuria',
	'Josefin Sans',
	'Josefin Slab',
	'Joti One',
	'Jua',
	'Judson',
	'Julee',
	'Julius Sans One',
	'Junge',
	'Jura',
	'Just Another Hand',
	'Just Me Again Down Here',
	'Kadwa',
	'Kalam',
	'Kameron',
	'Kanit',
	'Kantumruy',
	'Karla',
	'Karma',
	'Katibeh',
	'Kaushan Script',
	'Kavivanar',
	'Kavoon',
	'Kdam Thmor',
	'Keania One',
	'Kelly Slab',
	'Kenia',
	'Khand',
	'Khmer',
	'Khula',
	'Kirang Haerang',
	'Kite One',
	'Knewave',
	'Kotta One',
	'Koulen',
	'Kranky',
	'Kreon',
	'Kristi',
	'Krona One',
	'Kumar One Outline',
	'Kumar One',
	'Kurale',
	'La Belle Aurore',
	'Laila',
	'Lakki Reddy',
	'Lalezar',
	'Lancelot',
	'Lateef',
	'Lato',
	'League Script',
	'Leckerli One',
	'Ledger',
	'Lekton',
	'Lemon',
	'Lemonada',
	'Libre Barcode 128 Text',
	'Libre Barcode 128',
	'Libre Barcode 39 Extended Text',
	'Libre Barcode 39 Extended',
	'Libre Barcode 39 Text',
	'Libre Barcode 39',
	'Libre Baskerville',
	'Libre Franklin',
	'Life Savers',
	'Lilita One',
	'Lily Script One',
	'Limelight',
	'Linden Hill',
	'Lobster Two',
	'Lobster',
	'Londrina Outline',
	'Londrina Shadow',
	'Londrina Sketch',
	'Londrina Solid',
	'Lora',
	'Love Ya Like A Sister',
	'Loved by the King',
	'Lovers Quarrel',
	'Luckiest Guy',
	'Lusitana',
	'Lustria',
	'Macondo Swash Caps',
	'Macondo',
	'Mada',
	'Magra',
	'Maiden Orange',
	'Maitree',
	'Mako',
	'Mallanna',
	'Mandali',
	'Manuale',
	'Marcellus SC',
	'Marcellus',
	'Marck Script',
	'Margarine',
	'Marko One',
	'Marmelad',
	'Martel Sans',
	'Martel',
	'Marvel',
	'Mate SC',
	'Mate',
	'Maven Pro',
	'McLaren',
	'Meddon',
	'MedievalSharp',
	'Medula One',
	'Meera Inimai',
	'Megrim',
	'Meie Script',
	'Merienda One',
	'Merienda',
	'Merriweather Sans',
	'Merriweather',
	'Metal Mania',
	'Metal',
	'Metamorphous',
	'Metrophobic',
	'Michroma',
	'Milonga',
	'Miltonian Tattoo',
	'Miltonian',
	'Mina',
	'Miniver',
	'Miriam Libre',
	'Mirza',
	'Miss Fajardose',
	'Mitr',
	'Modak',
	'Modern Antiqua',
	'Mogra',
	'Molengo',
	'Molle',
	'Monda',
	'Monofett',
	'Monoton',
	'Monsieur La Doulaise',
	'Montaga',
	'Montez',
	'Montserrat Alternates',
	'Montserrat Subrayada',
	'Montserrat',
	'Moul',
	'Moulpali',
	'Mountains of Christmas',
	'Mouse Memoirs',
	'Mr Bedfort',
	'Mr Dafoe',
	'Mr De Haviland',
	'Mrs Saint Delafield',
	'Mrs Sheppards',
	'Mukta Mahee',
	'Mukta Malar',
	'Mukta Vaani',
	'Mukta',
	'Muli',
	'Mystery Quest',
	'NTR',
	'Nanum Brush Script',
	'Nanum Gothic Coding',
	'Nanum Gothic',
	'Nanum Myeongjo',
	'Nanum Pen Script',
	'Neucha',
	'Neuton',
	'New Rocker',
	'News Cycle',
	'Niconne',
	'Nixie One',
	'Nobile',
	'Nokora',
	'Norican',
	'Nosifer',
	'Nothing You Could Do',
	'Noticia Text',
	'Noto Sans',
	'Noto Serif',
	'Nova Cut',
	'Nova Flat',
	'Nova Mono',
	'Nova Oval',
	'Nova Round',
	'Nova Script',
	'Nova Slim',
	'Nova Square',
	'Numans',
	'Nunito Sans',
	'Nunito',
	'Odor Mean Chey',
	'Offside',
	'Old Standard TT',
	'Oldenburg',
	'Oleo Script Swash Caps',
	'Oleo Script',
	'Open Sans Condensed',
	'Open Sans',
	'Oranienbaum',
	'Orbitron',
	'Oregano',
	'Orienta',
	'Original Surfer',
	'Oswald',
	'Over the Rainbow',
	'Overlock SC',
	'Overlock',
	'Overpass Mono',
	'Overpass',
	'Ovo',
	'Oxygen Mono',
	'Oxygen',
	'PT Mono',
	'PT Sans Caption',
	'PT Sans Narrow',
	'PT Sans',
	'PT Serif Caption',
	'PT Serif',
	'Pacifico',
	'Padauk',
	'Palanquin Dark',
	'Palanquin',
	'Pangolin',
	'Paprika',
	'Parisienne',
	'Passero One',
	'Passion One',
	'Pathway Gothic One',
	'Patrick Hand SC',
	'Patrick Hand',
	'Pattaya',
	'Patua One',
	'Pavanam',
	'Paytone One',
	'Peddana',
	'Peralta',
	'Permanent Marker',
	'Petit Formal Script',
	'Petrona',
	'Philosopher',
	'Piedra',
	'Pinyon Script',
	'Pirata One',
	'Plaster',
	'Play',
	'Playball',
	'Playfair Display SC',
	'Playfair Display',
	'Podkova',
	'Poiret One',
	'Poller One',
	'Poly',
	'Pompiere',
	'Pontano Sans',
	'Poor Story',
	'Poppins',
	'Port Lligat Sans',
	'Port Lligat Slab',
	'Pragati Narrow',
	'Prata',
	'Preahvihear',
	'Press Start 2P',
	'Pridi',
	'Princess Sofia',
	'Prociono',
	'Prompt',
	'Prosto One',
	'Proza Libre',
	'Puritan',
	'Purple Purse',
	'Quando',
	'Quantico',
	'Quattrocento Sans',
	'Quattrocento',
	'Questrial',
	'Quicksand',
	'Quintessential',
	'Qwigley',
	'Racing Sans One',
	'Radley',
	'Rajdhani',
	'Rakkas',
	'Raleway Dots',
	'Raleway',
	'Ramabhadra',
	'Ramaraja',
	'Rambla',
	'Rammetto One',
	'Ranchers',
	'Rancho',
	'Ranga',
	'Rasa',
	'Rationale',
	'Ravi Prakash',
	'Redressed',
	'Reem Kufi',
	'Reenie Beanie',
	'Revalia',
	'Rhodium Libre',
	'Ribeye Marrow',
	'Ribeye',
	'Righteous',
	'Risque',
	'Roboto Condensed',
	'Roboto Mono',
	'Roboto Slab',
	'Roboto',
	'Rochester',
	'Rock Salt',
	'Rokkitt',
	'Romanesco',
	'Ropa Sans',
	'Rosario',
	'Rosarivo',
	'Rouge Script',
	'Rozha One',
	'Rubik Mono One',
	'Rubik',
	'Ruda',
	'Rufina',
	'Ruge Boogie',
	'Ruluko',
	'Rum Raisin',
	'Ruslan Display',
	'Russo One',
	'Ruthie',
	'Rye',
	'Sacramento',
	'Sahitya',
	'Sail',
	'Saira Condensed',
	'Saira Extra Condensed',
	'Saira Semi Condensed',
	'Saira',
	'Salsa',
	'Sanchez',
	'Sancreek',
	'Sansita',
	'Sarala',
	'Sarina',
	'Sarpanch',
	'Satisfy',
	'Scada',
	'Scheherazade',
	'Schoolbell',
	'Scope One',
	'Seaweed Script',
	'Secular One',
	'Sedgwick Ave Display',
	'Sedgwick Ave',
	'Sevillana',
	'Seymour One',
	'Shadows Into Light Two',
	'Shadows Into Light',
	'Shanti',
	'Share Tech Mono',
	'Share Tech',
	'Share',
	'Shojumaru',
	'Short Stack',
	'Shrikhand',
	'Siemreap',
	'Sigmar One',
	'Signika Negative',
	'Signika',
	'Simonetta',
	'Sintony',
	'Sirin Stencil',
	'Six Caps',
	'Skranji',
	'Slabo 13px',
	'Slabo 27px',
	'Slackey',
	'Smokum',
	'Smythe',
	'Sniglet',
	'Snippet',
	'Snowburst One',
	'Sofadi One',
	'Sofia',
	'Song Myung',
	'Sonsie One',
	'Sorts Mill Goudy',
	'Source Code Pro',
	'Source Sans Pro',
	'Source Serif Pro',
	'Space Mono',
	'Special Elite',
	'Spectral SC',
	'Spectral',
	'Spicy Rice',
	'Spinnaker',
	'Spirax',
	'Squada One',
	'Sree Krushnadevaraya',
	'Sriracha',
	'Stalemate',
	'Stalinist One',
	'Stardos Stencil',
	'Stint Ultra Condensed',
	'Stint Ultra Expanded',
	'Stoke',
	'Strait',
	'Stylish',
	'Sue Ellen Francisco',
	'Suez One',
	'Sumana',
	'Sunflower',
	'Sunshiney',
	'Supermercado One',
	'Sura',
	'Suranna',
	'Suravaram',
	'Suwannaphum',
	'Swanky and Moo Moo',
	'Syncopate',
	'Tajawal',
	'Tangerine',
	'Taprom',
	'Tauri',
	'Taviraj',
	'Teko',
	'Telex',
	'Tenali Ramakrishna',
	'Tenor Sans',
	'Text Me One',
	'The Girl Next Door',
	'Tienne',
	'Tillana',
	'Timmana',
	'Tinos',
	'Titan One',
	'Titillium Web',
	'Trade Winds',
	'Trirong',
	'Trocchi',
	'Trochut',
	'Trykker',
	'Tulpen One',
	'Ubuntu Condensed',
	'Ubuntu Mono',
	'Ubuntu',
	'Ultra',
	'Uncial Antiqua',
	'Underdog',
	'Unica One',
	'UnifrakturCook',
	'UnifrakturMaguntia',
	'Unkempt',
	'Unlock',
	'Unna',
	'VT323',
	'Vampiro One',
	'Varela Round',
	'Varela',
	'Vast Shadow',
	'Vesper Libre',
	'Vibur',
	'Vidaloka',
	'Viga',
	'Voces',
	'Volkhov',
	'Vollkorn SC',
	'Vollkorn',
	'Voltaire',
	'Waiting for the Sunrise',
	'Wallpoet',
	'Walter Turncoat',
	'Warnes',
	'Wellfleet',
	'Wendy One',
	'Wire One',
	'Work Sans',
	'Yanone Kaffeesatz',
	'Yantramanav',
	'Yatra One',
	'Yellowtail',
	'Yeon Sung',
	'Yeseva One',
	'Yesteryear',
	'Yrsa',
	'Zeyada',
	'Zilla Slab Highlight',
	'Zilla Slab'
);

$llp_google_fonts = array();
foreach( $llp_font_array as $font ) {
	$llp_google_fonts[ $font ] = $font;
}
